apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unified-health.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMaps.app.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
