{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "unified-health.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unified-health.api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: unified-health-api
      {{- include "unified-health.selectorLabels" . | nindent 6 }}

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "unified-health.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unified-health.web.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: unified-health-web
      {{- include "unified-health.selectorLabels" . | nindent 6 }}
{{- end }}
