---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unified-health.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unified-health.api.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
      protocol: {{ .Values.service.api.protocol }}
      name: http
  selector:
    app: unified-health-api
    {{- include "unified-health.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unified-health.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unified-health.web.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
      protocol: {{ .Values.service.web.protocol }}
      name: http
  selector:
    app: unified-health-web
    {{- include "unified-health.selectorLabels" . | nindent 4 }}
