{{- if and .Values.enabled .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "personalization-service.fullname" . }}
  labels:
    {{- include "personalization-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
