apiVersion: v1
kind: Namespace
metadata:
  name: healthcare-africa
  labels:
    name: healthcare-africa
    region: africa
    environment: production
    istio-injection: enabled
  annotations:
    description: "Healthcare Platform - Africa Region"
