{{- if and .Values.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "localization-service.serviceAccountName" . }}
  labels:
    {{- include "localization-service.labels" . | nindent 4 }}
  annotations:
    {{- include "localization-service.irsaAnnotation" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
{{- end }}
